// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfGGnFOR_cPHdlNKvlofxA-6i__CEr6nc',
    appId: '1:998086120823:web:7177eca055c90790c2bd72',
    messagingSenderId: '998086120823',
    projectId: 'jobpop-464001',
    authDomain: 'jobpop-464001.firebaseapp.com',
    storageBucket: 'jobpop-464001.firebasestorage.app',
    measurementId: 'G-J0CCB5J468',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV8DaSEEB1QqoWpBXIEHRI22OliPUUTUM',
    appId: '1:998086120823:android:a1db6dab319b731fc2bd72',
    messagingSenderId: '998086120823',
    projectId: 'jobpop-464001',
    storageBucket: 'jobpop-464001.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClyrlE_dR3ajpwzg5vB73YeKRPIEvS6Cw',
    appId: '1:998086120823:ios:d80ce6b570abe0f0c2bd72',
    messagingSenderId: '998086120823',
    projectId: 'jobpop-464001',
    storageBucket: 'jobpop-464001.firebasestorage.app',
    iosBundleId: 'com.example.jobpopp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClyrlE_dR3ajpwzg5vB73YeKRPIEvS6Cw',
    appId: '1:998086120823:ios:d80ce6b570abe0f0c2bd72',
    messagingSenderId: '998086120823',
    projectId: 'jobpop-464001',
    storageBucket: 'jobpop-464001.firebasestorage.app',
    iosBundleId: 'com.example.jobpopp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfGGnFOR_cPHdlNKvlofxA-6i__CEr6nc',
    appId: '1:998086120823:web:0267ffdd5f85750cc2bd72',
    messagingSenderId: '998086120823',
    projectId: 'jobpop-464001',
    authDomain: 'jobpop-464001.firebaseapp.com',
    storageBucket: 'jobpop-464001.firebasestorage.app',
    measurementId: 'G-FSKG43GM2X',
  );
}
